### ISSUE TITLE
Disallow Routes

### ISSUE THREAD

**Issue by aceptra** [Finbuckle/Finbuckle.MultiTenant#107]
Looking for sample code regarding routing only to login-logout and tenant routes.

        private void ConfigRoutes(IRouteBuilder routes)
        {
            routes.MapRoute("Default", "{__tenant__=}/{controller=SomeController}/{action=Index}");
            routes.MapRoute("Login", "{controller=Account}/{action=Login}");
        }

As per examples **ConfigRoutes** is called by both service setup **WithRouteStrategy** and UseMvc in the pipeline.

Perhaps I'm having a misunderstanding of routing, but would like routes that don't provide "__tenant__" to not work.

Any guidance is appreciated.

**Comment by AndrewTriesToCode** [comment]
Hi @aceptra 

If you just had the first route then a tenant would be required in the path--any other request would fail.

However your second route, which defaults to Account/Login, is letting anything else through without a tenant. Are you trying to have a common login page that doesn't care about the current tenant? If so then just a route of `routes.MapRoute("Login", "Account/Login", { controller = "Account", Action = "Login");` would work without allowing other controllers and actions to match.

If you are using per-tenant authentication options this will be problematic though because the login page won't know who the current tenant is. Check out the IdentityDataIsolation sample to see how I set it up to have `tenant/Account/Login` Path with Identity.

It would be possible to have a shared login page, without tenant in the path, that detects tenant based on the login email address, but I don't currently have an example of this yet.

Please let me know how I can help!

**Comment by aceptra** [comment]
I think I got what I need based on your response. FYI, I'm using Auth0 for SSO/

I originally tried a shared login URL 

I'm trying now without the "login" route, just using the "default" route as per your samples:
            routes.MapRoute(
                name: "default", 
                template: "{__tenant__}/{controller}/{action}",
                defaults: new { __tenant__ = "", controller = "Home", action = "Index"}
            );

Only difference is some clients might use different SSO connections from there, passed via a Auth0 "Connection" parameter in the query string. I have that taken care of with the WithPerTenantOptions.

Still having some trouble though with default routes. Everything is fine if I manually browse:

**http://localhost:53155/tenant1/Account/Login**  <-- for Login. It will use the Auth0 Connection type per tenant and forward to the appropriate SSO login screen. 

Manual nav to **http://localhost:53155/tenant1/AnyOtherController/AnyView** also works as expected if manually put in at some point. Url.Action links also work. Trying a different tenant redirects you to login, as expected. 

(Would like Visual Studio debug-run to default to a specific tenant, or redirect maybe. I suppose a non issue b/c clients will attempt to login with their "http://localhost:53155/<tenantIdentifier>/Account/Login" URL. If you have a way to default to a specific tenant login let me know.)


Or... just if you have time, I might like to have an example of detecting login based off a Claim or Email. Sorry I know that might be asking a bit much.

You've been a great help.

**Comment by AndrewTriesToCode** [comment]
With regard to a default tenant, you an set a default route parameter like so:
```
routes.MapRoute("Default", "{__tenant__=DefaultTenant}/{controller=SomeController}/{action=Index}");
```

You could also create your own `IMultiTenantStrategy` which falls back to a default, but that is a little more complicated.

@aceptra sorry for the slow reply. I plan to have a sample based on email for a shared login page early this week. A claims-based is an interesting idea--I will think about how that might work too.

**Comment by aceptra** [comment]
No problem at all with the delay. I appreciate your insight.

I look forward to your examples using shared login with email as a tenant identifier. We will likely use something in claims as the identifier.

Thanks again!

**Comment by AndrewTriesToCode** [comment]
@aceptra I'm curious, where will you get the claims from? In your case are you routing all people to the same external identity provider?

**Comment by aceptra** [comment]
Yes at the moment all are going through same identity provider. Tenancy as divided up by some kind of user metadata.

I'm thinking the userinfo of Auth0. We're still in the planning of this, so not locked in. And for transparency sake I'm not sure if that is actually the set of claims or not (token claim). It is a little bit of a new subject for me.

I wonder if the muiltiple per-tenant login is a better approach and scales better should the need arise. In the meantime all tenants can just point to the same place (configurable).

**Comment by AndrewTriesToCode** [comment]
@aceptra Hi I just merged a PR with a new sample for a shared login page--I hope you can see from that how it might work using claims instead of email address.

You could have the best of both worlds by doing per tenant OpenID connect options -- for most tenants have them point to the same identity provider (like you have now), then if any tenant wants to use their own identity provider for SSO or similar you can simply change the per-tenant-options for that single tenant.

Happy coding!

**Comment by aceptra** [comment]
Closing this for now. I got what I need... I think. I see the new sample.

Thanks again.
