### ISSUE TITLE
Identity DbContext CacheFactory Bug

### ISSUE THREAD

**Issue by wros** [Finbuckle/Finbuckle.MultiTenant#109]
Hi i got this bug on Identity **DbContext**  cache resolution. If use a derived base class with three or more generic arguments, the tenant is not change.

Sorry for the bad english.

Original Code:

```
...
if (currentType.IsGenericType && currentType.GetGenericTypeDefinition() == typeof(MultiTenantIdentityDbContext<>))
{
 return true;
}
...
```

My workaround

```
...
if (currentType.IsGenericType && (currentType.GetGenericTypeDefinition() == typeof(MultiTenantIdentityDbContext<>) || currentType.GetGenericTypeDefinition() == typeof(MultiTenantIdentityDbContext<,,>) || currentType.GetGenericTypeDefinition() == typeof(MultiTenantIdentityDbContext<,,,,,,,>)))
{
 return true;
}
...
```

**Comment by AndrewTriesToCode** [comment]
@wros Hi, thank you for finding this bug! Your English is very good, no problem!

Looking at the code I just realized that all the `MultiTenantIdentitityDbContext` types all derive from `MultiTenantIdentityDbContext<,,,,,,,>` so I can probably simplify the entire function to something like:

```
private bool ContextDerivesFromMultiTenantIdentityDbContext(DbContext context)
{
    return typeof(MultiTenantIdentityDbContext<,,,,,,,>).IsAssignableFrom(currentType); 
}
```

I can't remember if I tried this before and because of generics it didn't work, hence my current code (which would need to be fixed your way).

I will look into it. What do you think?

**Comment by wros** [comment]
@achandlerwhite Hi,

I tested your code, but generic type fails on comparison. This method only work if use **.GetGenericTypeDefinition()** but the result is the same of my previous code and more complex.  I attached a image of the VS watch.

![image](https://user-images.githubusercontent.com/26489708/51636004-46a30400-1f3f-11e9-8d1b-57cdc29c4a01.png)

**Comment by wros** [comment]
Sorry, I closed it by mistake.

**Comment by AndrewTriesToCode** [comment]
@wros You are right. You're fix is the right way to go. Do you want to submit a pull request?

**Comment by wros** [comment]
@achandlerwhite 

 You can include it in an existing PR, no problem.
