### ISSUE TITLE
Can't update record

### ISSUE THREAD

**Issue by ericsports** [Finbuckle/Finbuckle.MultiTenant#117]
When trying to update a record for a simple class, I am getting the following error message:

`MultiTenantException: 1 modified entities with TenantId not set.`

Looking directly at the database, I can see that the TenantID is set just fine when the record was created.

Any ideas why this may be happening?

**Comment by AndrewTriesToCode** [comment]
Hi @ericsports

It might be set in the database but for some reason the entity in memory doesn’t have it set. Can you link me to a simple project that recreates the problem? I’d be happy to take a look.

**Comment by ericsports** [comment]
@achandlerwhite Thanks for the reply, I have sent you a message with the project attached.

**Comment by AndrewTriesToCode** [comment]
Thanks @ericsports I got the project. I was able to start it up and run it. I did change the Sql Server database to use the in-memory variant because I'm on a Mac (haven't tried setting up Sql Server on it yet).

I see you have the localhost resolving to the "baxter" tenant. I am able to register a user with Identity and was able to update the phone number for that user.

What was it in the app that triggered the error message for you?

**Comment by ericsports** [comment]
Thanks for looking at it!  It was the SiteSettings found in the models folder (there is already a controller set up, you can access it at /SiteSettings)

I can create new ones, delete them, but if I go to edit and save, that's when I got the error.

**Comment by AndrewTriesToCode** [comment]
Thanks. I will take a look tomorrow.

**Comment by ericsports** [comment]
Thanks @achandlerwhite , appreciate it!

**Comment by ericsports** [comment]
I've gone ahead and downloaded the actual samples and tried to add a simple class (with proper annotation) to that and scaffold it as well.  Same outcome directly from the samples, can create, can delete, but get that same error when trying to update.

**Comment by AndrewTriesToCode** [comment]
Hi again, I see the issue.

Because you are using `_context.Update(siteSettings)` to do a direct update the tenant id is not set on the "untracked" entity because tenant id is a shadow property in EFCore.

You have a few options:
1) Use `TenantNotSetMode.Overwrite` which will plug in the tenant Id when saving. Note that this settings will be in effect for any future saves on the same dbcontext in the request.
```
_context.TenantNotSetMode = TenantNotSetMode.Overwrite;
_context.Update(siteSettings);
await _context.SaveChangesAsync();
```
2) You can add a property to the `SiteSettings` class called `TenantId` which Finbuckle.MultiTenant will use, then if you make sure it gets passed around in the Get/Post requests the tenant Id should be there when you call `Update` and `SaveChanges`.

3) Avoid using `Update` and instead get the entity from the database via EFCore then update this "tracked" entity, then save it.
```
var siteSettings = await _context.SiteSettings.FirstOrDefaultAsync(m => m.Id == id);
siteSettings.Prop1 = model.Prop1;
siteSettings.Prop2 = model.Prop2;
// etc..
await _context.SaveChangesAsync();
```

I think option 1 is probably the best way to go here.

**Comment by ericsports** [comment]
Thanks for the explanation, really appreciate your help.
