### ISSUE TITLE
Allow optional wrapping of stores and strategies

### ISSUE THREAD

**Issue by WalternativE** [Finbuckle/Finbuckle.MultiTenant#159]
## What is the problem?

I'm currently facing the following issue: until recently (I think 3.1.0) store implementations didn't use to get wrapped. This allowed me to do some "rather unclean" things like implementing the store interface, requiring the store interface via DI and then pattern match on my custom implementation to get more functionality (like a `GetAllTenants` method). Using the included extension methods I can't register unwrapped types anymore which currently breaks me in runtime.

## Why do I do those hacky things?

I have two cases in which this hacky way of working with DI is quite useful for me.

1) In development when starting up the application and applying automatic migrations on all known dev tenants
2) In integration tests when dynamically doing the same for in-memory databases

## What workarounds do I currently have?

I can write my own extension methods to add strategies. I suppose that's the cleanest way of doing it right now. I can also revert to 3.0.1 where the wrapping doesn't happen yet.

## Possible solutions?

1) Make wrapping optional (would be nice anyway as I might to do all my logging on my own)
2) Expose the wrapped Type via an accessor in the wrapper (not really beautiful though)

What do you think about it? I personally would go with option one but maybe I don't have the full picture. If you think that this would be a sensible approach I could prepare a PR.

Kind regards
Gregor

**Comment by AndrewTriesToCode** [comment]
@WalternativE Hi thanks for this feedback and your other comment.

In taking a quick look at the code I think I want to have it so the instance stored in the MultiTenantContext is the "inner" one -- I already adjusted the code to show the Type of the inner one so it would make sense that the inner one does too. I'll probably add a property to the wrapper class to access the inner instance for this purpose.

Thanks!

**Comment by WalternativE** [comment]
@achandlerwhite Thank you for the update! If anything comes up where I could be of assistance just shoot me a message.

Cheers!

**Comment by AndrewTriesToCode** [comment]
@WalternativE I think it will be relatively easy. I am trying to shape up a pretty significant PR related to an http based multitenant store which is taking longer than I intended. If you want to take a stab at this and submit a PR feel free. Otherwise your feedback on my PR will be nice.

Here are the specifics I have in mind:

1.  Add a property to the wrapper for both store and strategy to expose the internal.
2. Unit tests for above
3. Modify [MultiTenantMiddleware](https://github.com/Finbuckle/Finbuckle.MultiTenant/blob/master/src/Finbuckle.MultiTenant.AspNetCore/Internal/MultiTenantMiddleware.cs) class so that it sets the 'StoreInfo.Store' and `StrategyInfo.Strategy` properties to the "inner" properties on the wrapper.
4. Unit tests for above
5. Adjust documentation for `MultiTenantContext`

**Comment by AndrewTriesToCode** [comment]
@WalternativE 

I just opened PR #161 to improve this. Take a quick look and let me know if that would help out for your use case. The wrapper's inner store/strategy is now public and the `StoreInfo.Store` and `StrategyInfo.Strategy` on `MultiTenantContext` now refer to the inner instances.

**Comment by WalternativE** [comment]
@achandlerwhite 

I took a look at the PR and it looks like exactly the thing I need for my use case :) Thank you very much!
