### ISSUE TITLE
When does the TenantInfo value sets in pipeline? 

### ISSUE THREAD

**Issue by IamGanesh19** [Finbuckle/Finbuckle.MultiTenant#164]
@achandlerwhite good job in creating this simple & great library for Multi Tenant support. I am using this in one of my project & works great. 

I am facing an issue in setting up [Configuration](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-2.2) per tenant. I have tenant specific configurations in SQL Table (with TenantId column) and using Custom Configuration Provider to fetch it via EF Core as shown in this [article](https://medium.com/@dneimke/custom-configuration-in-net-core-2-193ff6f02046). As this is happening before the Startup, TenantInfo is not set. Hence the configuration provider is pulling out all the configuration irrespective of current tenant. Is there a way to achieve what I am trying with this library?

**Comment by AndrewTriesToCode** [comment]
Hello @IamGanesh19   sorry for the slow reply.

In the pipeline the `UseMultiTenant` called the middleware which actually sets the current multitenant context.

Your situation is interesting. This library was designed with per-tenant options in mind, but not per-tenant configuration... however options are often directly created from configuration so this might be doable.

When the configuration provider's `TryGet` method you will need to know the current tenant to adjust your database call accordingly. One way to do that would be to inject `MultiTenantContextAccessor` into the provider and during each `TryGet` it can check to see the current tenant (if there is one) and act accordingly. I don't know if the configuration provider constructor uses dependency injection, but if not maybe the configuration source does, and it can pass the `MultiTenantContextAccessor` to the provider which can store it.

I can think of a few caveats - how you access the configuration will affect when the provider's `TryGet` is called. If using options then `IOptions` will only do it once the first time. `IOptionsSnapshot` will do it once per request, and `IOptionsMonitor` is somewhere in the middle. `IOptionsSnapshot` would be good to use for any settings your code accesses, but if you are wanting to have per-tenant configuration for settings other part of ASP.NET Core then there is not an easy way to know which options type they use. Another thing you could do is skip options and load the config directly with `IConfiguration` which normally you do only in startup but I think you can do it in a controller or midleware too. I think it will call the provider's `TryGet` mthod.

Finally, in your provider you will probably want to implement some sort of caching so that every request isn't a database hit to load the config.

I hope this makes sense! Let me know how it goes.
