### ISSUE TITLE
Question about Usermanager.CreateAsync

### ISSUE THREAD

**Issue by stardocs-digital** [Finbuckle/Finbuckle.MultiTenant#200]
This isn't an issue but more like a question.

I'm learning how to use Finbuckle and was curious as to how you managed to get Usermanager.CreateAsync to allow duplicate usernames? I understand that your tenantId is different but in a normal scenario. Wouldn't Usermanager.CreateAsync return a duplicate username error?

**Comment by AndrewTriesToCode** [comment]
hi @stardocs-services 
sorry for the late reply! it works because internally `CreateAsync` calls `UserStore.GetUserByUsername` (or something very similar can't recall off the top of my head) which queries EFCore by username to see if one already exists. However the Finbuckle.MultiTenant global query filter is applied so it basically adds an extra `where tenantId = __current_tenant__` to that query so if it only returns one for that same query. Does that make sense?
