### ISSUE TITLE
Why not store items in EFCoreStoreDbContext?

### ISSUE THREAD

**Issue by chadbengen** [Finbuckle/Finbuckle.MultiTenant#212]
I'm curious about why the EFCoreStoreDbContext ignores the Items property?  Why not store it as json?  I think something like this:

```c#
modelBuilder.Entity<TentantInfo>()
     .Property(b => b.Items)
     .HasConversion(
          v => JsonConvert.SerializeObject(v),
          v => JsonConvert.DeserializeObject<Dictionary<string, object>>(v));
```

**Comment by AndrewTriesToCode** [comment]
Hi @chadbengen 

It certainly could be but it’s a little more complicated because when deserializing we don’t know the correct type. Also I’d want to build it in such a way that it is flexible for all users— I.e. provide reasonable defaults but let devs configure the serialization and deserialization. I’m open to ideas and PRs!

Taking a quick look I realized that Newtonsoft can handle the type preservation. I think with that I can add this pretty easily.

**Comment by chadbengen** [comment]
Great, i look forward to it.

**Comment by AndrewTriesToCode** [comment]
Doing a little cleanup -- with the move to custom `ITenantInfo` implementations `Items` is no longer used anymore.
