### ISSUE TITLE
Foreign key consistency with Tenants table

### ISSUE THREAD

**Issue by mphill** [Finbuckle/Finbuckle.MultiTenant#224]
When using the EF Core storage for Tenants, and Identity, you have to have two different contexts:

1. EFCoreStoreDbContext
2. MultiTenantIdentityDbContext

As a result the TenantId is decoupled from your main models in MultiTenantIdentityDbContext.

This introduces a host of issues, like if you want to change the TenantId (perhaps a domain change on the routing strategy) - a cascade update would allow this. Instead of having to manually update all the tables.

Also you cannot setup unique keys that includes the TenantId. For instance an Employees table with EmployeeId and TenantId.

Is there a way to handle this situation?

Thanks!

**Comment by AndrewTriesToCode** [comment]
hi @mphill 

My thought process was that `TenantId` should never change, but `TenantIdentifier` could change over time. The multitenant strategies and stores primarily use `TenantIdentifier` for their lookups. In your example of host lookup that would be against the `TenantIdenfier` rather than the `TenantId` column.

The reason I have 2 separate contexts in my examples are because I consider the store information (whether EFCore store or something else) to belong to the application and the Identity database to belong to the tenant.

For Identity I want each tenant to essentially have its own "isolated" database.

In order to accomplish that the application's middleware (via strategies and stores) need to do their thing to determine the current tenant for a request. So the EFCore store is used even before a tenant is known and the application needs to see them all.

They could in theory be combined into a single DbContext -- the `TenantInfo` entity would just not be designated as multitenant like the Identity entities are by default.

I hope that makes sense and I hope it helps! Let me know!

**Comment by mphill** [comment]
@achandlerwhite 

This makes perfect sense.  The fact the `TenantIdentifier` is the discriminator definitely puts my initial concern to rest.

In my use case, I want to have 1 shared database to keep costs and maintenance lower so I don't even use the connection string.  Would you still say this is a perfectly acceptable and supported use case for your library?



As for the unique key, I think I found a solution - I just want to run it past you.

For the entity you want a per-tenant unique constraint, add `public string TenantId { get; set; }`

For example: 

```
    public class Product
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public Guid Id { get; set; }

        public string Name { get; set; }
        
        [JsonIgnore]
        public string TenantId { get; set; }
    }

```

Then with the `modelBuilder`

`modelBuilder.Entity<Product>().IsMultiTenant().HasIndex(t => new { t.TenantId, t.Name }).IsUnique();`


This would in theory allow each tenant to have their own unique index per entity.  This seems to work but would like to validate it would not violate anything internally.

The solution may work, but obviously leaves a lot fo be desired.  

I think a better solution might be an extension method on `IsMutliTenant()`, say `HasMultiTenantUnique(t => t.Name)` that would be functionally the same as above but would but would not require the entity to understand what a TenantId is.

Thanks!

**Comment by AndrewTriesToCode** [comment]
I really like your idea for `HasMultiTenantUnique` or `HasMultiTenantIndex`. I'll tag this as an enhancement. Feel free to submit a PR if you are feeling ambitious, otherwise I think I'll try to work on it in the near future.

**Comment by mphill** [comment]
The proposed change is in this commit:

https://github.com/mphill/Finbuckle.MultiTenant/commit/74b92ef19a7e4cdf167bcd50434fa58ab13aeca4

By returning `IndexBuilder` you have the option to chain `IsUnique()`

This allows both indexes and unique indexes to now incorporate `TenantId`

**Comment by AndrewTriesToCode** [comment]
over a year later -- sorry for the slow response!

I recently added `AdjustIndex`, `AdjustUniqueIndexes`, and `AdjustIndexes` as well as `AdjustKey` building on your idea. I wanted to modify existing keys/indexes set via the normal EFCore methods rather than replace them.

Look for them in the next release coming up soonish. (.NET 6 timeframe or earlier)
