### ISSUE TITLE
If you include objects in the tenant's Items in appsettings.json, the read will report an error

### ISSUE THREAD

**Issue by alonsoalon** [Finbuckle/Finbuckle.MultiTenant#236]
If you include objects in the tenant's Items in appsettings.json, the read will report an error,
eg:
"Items": { 
   "configExample":{"key":"1"} // []
} 
Error source location:
Finbuckle.MultiTenant.Core\Stores\ConfigurationStore\ConfigurationStore.cs
line number : 65

**Comment by AndrewTriesToCode** [comment]
@alonsoalon Thanks for reporting this. I'll take a look.

**Comment by Hammurabidoug** [comment]
In an attempt to overcome this issue, I inherited from TenantInfo with a class that contains additional configuration properties. I had to create my own IMultiTenantStore named CustomConfigurationStore. The UpdateTenantMap method looks like:

```
        private void UpdateTenantMap()
        {
            var newMap = new ConcurrentDictionary<string, TenantInfo>(StringComparer.OrdinalIgnoreCase);
            var tenants = section.GetSection("Tenants").GetChildren();

            foreach (var tenantSection in tenants)
            {
                var defaultsSection = section.GetSection("Defaults");

                var newTenant = defaultsSection.Get<DerivedTenantInfo>(options =>
                {
                    options.BindNonPublicProperties = true;
                });
                tenantSection.Bind(newTenant, options => options.BindNonPublicProperties = true);
                newMap.TryAdd(newTenant.Identifier, newTenant);
            }

            var oldMap = tenantMap;
            tenantMap = newMap;
        }
```

It binds DerivedTenantInfo instead of TenantInfo.


```
    public class DerivedTenantInfo : TenantInfo
    { 
        public MySubOptions SubOptions { get; set; }
    }

    public class MySubOptions
    {
        public string Value1 { get; set; }
        public string Value2 { get; set; }
    }
```
In the appsettings file:
```
    "Defaults": {
      "MySubOptions": {
        "Value1": "the object's first value",
        "Value2": "the object's second value"
      },

```
When I add per-tenant options in the Startup.ConfigureServices,
```
            services.AddMultiTenant()
                .WithStore<CustomConfigurationStore>(ServiceLifetime.Singleton)
                .WithDelegateStrategy(async context =>
                {
                    HttpContext httpContext = (HttpContext)context;
                    PathString pathString = httpContext.Request.PathBase;
                    var tenantId = await Task.FromResult(pathString.Value.Trim('/')).ConfigureAwait(false);
                    return tenantId;
                })
                .WithPerTenantOptions<MySubOptions>((options, tenantInfo) =>
                {
                    var customTenantInfo = tenantInfo as DerivedTenantInfo;

                    if (customTenantInfo != null)
                    {
                        options = customTenantInfo.SubOptions;
                    }

                });
```
The values get set properly in the WithPerTenantOptions method, but when the options get injected, the values are empty. I suspect it has something to do with how the TenantInfo is retrieved from the HttpContext.

**Comment by AndrewTriesToCode** [comment]
@Hammurabidoug do you have a repository of this I can clone and try out?

**Comment by Hammurabidoug** [comment]
I'll whip one up.

Doug Simpson

**Comment by Hammurabidoug** [comment]
https://github.com/Hammurabidoug/Finbuckle.ObjectOptions

**Comment by Hammurabidoug** [comment]
I'm not sure how you would do this because I haven't dug deep into Finbuckle, but it would be nice to have a `ConfigurationStore<T> where T : TenantInfo`. This class might allow users to use strongly typed object properties. I personally would like my custom TenantInfo to contain CorsOptions, OpenIdConnectOptions, AuthorizationOptions, AuthenticationOptions, and a slew of other per-tenant options. Using a Dictionary that requires <string, string> makes organization of the appsettings difficult with so many per-tenant options.

I love what you've done, though. The IOptions per tenant approach is much, much cleaner and manageable than the DI approach like AutoFac and others use.

**Comment by AndrewTriesToCode** [comment]
@Hammurabidoug thanks. The `ConfigurationStore` was originally intended to be a bare bones implementation I could use in samples and stuff--but I like your ideas. Thanks for the repo I'll take a look.

**Comment by AndrewTriesToCode** [comment]
@Hammurabidoug 

I rigged it up with the library source code and stepped through it all. Turns out its a simple pass-by-value issue. You can't totally replace the `options` object itself because it isn't passed into this delegate by reference. But if you set each property like below it works:

```
.WithPerTenantOptions<MySubOptions>((options, tenantInfo) =>
{
    var derivedTenantInfo = tenantInfo as DerivedTenantInfo;

    if (derivedTenantInfo != null)
    {
        //options = derivedTenantInfo.SubOptions; // reassigning options won't "stick"
        options.Value1 = derivedTenantInfo.SubOptions.Value1;
        options.Value2 = derivedTenantInfo.SubOptions.Value2;
    }
});
```

Also your delegate strategy wasn't working in the example... I change `BasePath` to `path` to make it work for the purpose of testing. Not sure what you are going for with that strategy but create another issue if you have any questions!

**Comment by Hammurabidoug** [comment]
Thanks. That'll work for now.

It seems like it wouldn't take much to map properties of one to the other in a "more elegant" fashion. I forked your repository and may try to add some features like this mapping and `ConfigurationStore<T>` if I have extra time. Now that I think about it, it may be possible to register all of the custom properties within a derived TenantInfo and only call a single WithPerTenantOption extension method that maps all of them. AutoMapper does something similar with reflection.

**Comment by Hammurabidoug** [comment]
I submitted a pull request to implement this feature. Let me know what you think.

**Comment by AndrewTriesToCode** [comment]
Doing a little cleanup -- we have since moved away from the `Items` collection on tenant info in favor of custom implementations so I'm going to close this one out.
