### ISSUE TITLE
Question API

### ISSUE THREAD

**Issue by KrishManohar** [Finbuckle/Finbuckle.MultiTenant#276]
I am looking for a solution for multi tenant for my API.

What I am trying to accomplish is:

1. Login Database (Single Database with all users, and tenant information / connection string)
2. After User Login an JWT token is generated, I want to put a unique tenant id in there as well.
3. For Each Request the API would send the tenant id via JWT and there in hand lookup the tenant info for connection string.

Maybe I am overthinking this...

Any help on the right direction is much appreciated.

**Comment by AndrewTriesToCode** [comment]
hi @KrishManohar, here are some thoughts

1. This makes perfect sense. No need for the login database to also be the multitenant store, but no harm if it also is.
2. Seems straight forward.
3. For this you'd want to either create a new implementation of `IMultiTenantStrategy` or use the delegate strategy. The logic would just check the JWT for the tenant and return it as the identifier--the middleware would do the rest. Depending on your setup you'll have to decide whether to use the middleware before or after the authentication middleware. If you place it after you can rely on the authentication validating the JWT. It might even make the tenant claim available to you in the current user claims principle instance. But then you wouldn't have per-tenant authentication options--might not be a problem for you.

Good luck!

**Comment by KrishManohar** [comment]
@AndrewTriesToCode Thank you for your response. I will try and see how it goes.
Thanks

**Comment by KrishManohar** [comment]
Hitting a little road block...

Is there and example of EF Store with Data Isolation? 

Basically 1 db context to  lookup identity &  and allow  login to identity users.
I will  pass the Tenant Info  via JWT and it  will get  pass back when the tenant needs data.

I  might need to take a  break  on this because it might be simple, and I am overthinking it.

**Comment by AndrewTriesToCode** [comment]
hi @KrishManohar 
I don't have an example pf EF Store with Data Isolation, but I can try to put one together later today.

I'd recommend a separate Db Context for the EFCore multitenant store and a separate one for your main application logic (and probably even a separate one for Identity). They can all work as a single Db Context but it becomes difficult to manage when migrations from one are affecting the other.

Another thing to look at is separate Db contexts but they all use the same database and connection string. You have to be careful there that the contexts don't interfere with each other, but it can work well.

**Comment by AndrewTriesToCode** [comment]
If you have a repository with your project or a sample showing the problems you are hitting I'd be happy to take a look.

**Comment by AndrewTriesToCode** [comment]
@KrishManohar I posted a modified `DataIsolationSample` [here](https://github.com/AndrewTriesToCode/Finbuckle.MultiTenant/tree/efcorestore-and-dateisolation/samples/ASP.NET%20Core%203/DataIsolationSample).

I'll probably clean this up and make it an official sample. I basically took the EFCoreStore from its sample and moved it into this sample. The main changes to the EFCoreStore sample dbcontext were to rename it to `MultiTenantStoreDbContext`, change it to use Sqlite, and to modify the constructor for `MultiTenantStoreDbContext` to take `DbContextOptions<MultiTenantStoreDbContext>` instead of the non-generic `DbContextOptions`. That last part is required if you use multiple db contexts in a single app.

Let me know if you have any questions.

**Comment by KrishManohar** [comment]
@AndrewTriesToCode perfect, thank you :)
