### ISSUE TITLE
Using RavenDB as store

### ISSUE THREAD

**Issue by bobskigit** [Finbuckle/Finbuckle.MultiTenant#283]
Has anyone experience of using this with RavenDB as the store?

**Comment by AndrewTriesToCode** [comment]
@bobskigit 
Hi Bob, I'm not aware of anythone using RavenDb as a store. If there is a EFCore provider for RavenDb then the EFCoreStore will **probably** work as-is. Otherwise it shouldn't be too difficult to implement `IMultiTenantStore` with the specifics needed to create/read/update/delete with RavenDb.

If you try it and run into any problems please let me know.

**Comment by bobskigit** [comment]
No worries, I've implemented it using IMultiTenantStore .

Well designed and documented library  BTW, looking forward to next version

**Comment by AndrewTriesToCode** [comment]
Excellent. FYI In the next version there will be a change to `IMultiTenantStore` to support custom `TenantInfo` classes. I doubt it will be major change to your implementation.
