### ISSUE TITLE
AuthenticationScheme per tenant using the MultiTenantAuthenticationSchemeProvider

### ISSUE THREAD

**Issue by alexjamesbrown** [Finbuckle/Finbuckle.MultiTenant#293]
Somewhat similar to https://github.com/Finbuckle/Finbuckle.MultiTenant/issues/104

    services.AddMultiTenant()
                .WithStaticStrategy("my-tenant")
                .WithRemoteAuthentication()
                .WithPerTenantOptions<AuthenticationOptions>((options, tenantInfo) =>
                {
                    if (tenantInfo.Items.TryGetValue("AuthenticationSchemes", out var authenticationSchemes))
                    {
                        var schemesForTenant = authenticationSchemes as IEnumerable<string>;

                        foreach (var schemeKey in schemesForTenant)
                        {
                            switch (schemeKey)
                            {
                                case "Google":
                                    options.AddScheme("Google", builder =>
                                    {
                                        builder.DisplayName = "Google";
                                        builder.HandlerType = typeof(GoogleHandler);
                                    });
                                    break;

                                case "Oidc":
                                    options.AddScheme("Oidc", builder =>
                                    {
                                        builder.DisplayName = "Oidc";
                                        builder.HandlerType = typeof(OpenIdConnectHandler);
                                    });
                                    break;
                            }
                        }
                    }
                })

In my `AccountController`, I do:
        var schemes = await _schemeProvider.GetAllSchemesAsync();

However, this doesn't return the schemes specific to this tenant (my-tenant).
It seems to return all of the schemes registered.

Is there a way to do this? This is because my login ui needs to list the available login schemes for this tenant.

Am I misunderstanding the `MultiTenantAuthenticationSchemeProvider`

**Comment by AndrewTriesToCode** [comment]
hi @alexjamesbrown, I apologize for the slow reply

The main reason for this class to to change how the Microsoft implementation handled options. It internally cached the options which means for a new request under a different tenant it wasn't using the correct per-tenant options--it was using the cached ones.

Otherwise it is the same as the standard `AuthenticationSchemeProvider`. I'd suggest storing the relevant schemes for each tenant as a part of the tenant info instance. The 6.0.0-preview releases let you define you own `TenantInfo` class so you can add a list of strings to it easily. If that doesn't sound like a good fit let me know--I always like to hear about good use cases.
