### ISSUE TITLE
Newbie question: How do I create a new tenant?

### ISSUE THREAD

**Issue by dwt12777** [Finbuckle/Finbuckle.MultiTenant#304]
Hey guys, huge apologies in advance as I am really a beginner programmer.  I have been reading the documentation and looking at the sample projects and am quite sure I'm overlooking something obvious.  But a couple of pointers would really help me out.  First, I'm trying to set up my project using the Host strategy pointed at a SQL server.  In my ConfigureServices method of the Startup class, I have:

`services.AddMultiTenant().WithEFCoreStore<ApplicationDbContext>().WithHostStrategy("__tenant__");`

I'll play with the string matching options, but just have the whole host in there to start with.

My ApplicationDbContext looks like this right now:

```
namespace ReardenNews.Web.Data
{
    public class ApplicationDbContext : EFCoreStoreDbContext
    {
        public ApplicationDbContext(DbContextOptions options) : base(options)
        {
        }

        public DbSet<ReardenNews.Models.Issue> Issue { get; set; }
        public DbSet<ReardenNews.Models.Newsletter> Newsletter { get; set; }
        public DbSet<ReardenNews.Models.Article> Article { get; set; }
  
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
        }
    }
}
```

And to start testing this, I've created a Tenants page with the intention of adding/editing/removing tenants (would eventually become my admin page in the project - individual tenants wouldn't have access to it (gotta start reading up on authorization...)

Anyway, on my mini-admin page I was trying to build the "create" capability - where I could start adding new tenants and that's where I hit a wall.  I realized I can't do something like this:

```
var myTenant = new TenantInfo();
myTenant.Identifier = "localhost";  // or bind it to a control where I'd input the identifier
...
```
This doesn't work because TenantInfo's properties are read only.  So I looked in the sample project "EFCoreStoreSample" I saw in the Startup class a method where some tenants were created like this:

```
private void SetupStore(IServiceProvider sp)
{
    var scopeServices = sp.CreateScope().ServiceProvider;
    var store = scopeServices.GetRequiredService<IMultiTenantStore<TenantInfo>>();
    store.TryAddAsync(new TenantInfo{ Id = "tenant-finbuckle-d043favoiaw", Identifier = "finbuckle", Name = "Finbuckle", ConnectionString = "finbuckle_conn_string"}).Wait();
    store.TryAddAsync(new TenantInfo{Id = "tenant-initech-341ojadsfa", Identifier = "initech", Name = "Initech LLC", ConnectionString = "initech_conn_string"}).Wait();
}
```
So I figured I'd try a similar approach, but I can't figure out how to access those objects like service providers from a regular page.   In short, I can't figure out:

1. How to add a new tenant from a page
2. How to list existing tenants
3. How to change tenant information then save it back to the database

Also, one related question: I have everything "wired up" (I believe) but I can't see that anything was actually created in the database.  Am I supposed to "update-database" or something like that to have it create the needed tables in the db?

Thanks in advance for your patience.  This is a great learning project for me, but I could really use a few pointers to get back on track.

**Comment by AndrewTriesToCode** [comment]
hi @dwt12777 
No worries about being a newbie -- I am definitely one in many areas.

This library provides the building blocks and you are on the right track. I actually plan to develop a full UI as a paid option for those interested -- but I highly encourage you to keep going!

A regular app that uses the multitenant store basically is read-only from it during tenant resolution. However a backend "admin" or maintenance app needs to populate the store. Each type of store can have its own way to do it -- ultimately if you are using a SQL Server database as the mlutitenant store all you need to do is insert the appropriate data into the tables.

In my sample which you looked at I was using the `EFCoreStore` which internally is just using Entity Framework core. The `IMultiTenantStore` `TryAddAsync` methods are simple and just do basic EFCore store create / save changes on the items.

In fact, if you are using EFCore or regular EF under the hood you could use it directly without the `IMultiTenantStore` part at all -- just inject your DB Context and start creating your `TenantInfo` objects. Finbuckle.MultiTenant would still use it as `IMultiTenantStore` in order to retrieve the tenant for each request.

Lastly I'll add that you don't need your main application db context to also be the EFCore context. You certainly can do this but you might not want to inherit your main app db context from `EFCoreStoreDbContext`. It might work better to have two different db context that even point to the same database. Of course you can go with a shared db context if it works for you.

Let me know if you have any more questions. Also I encourage you to look at the release 6.0.0 previews since they let you customize the tenant store class. Although I think there is a bug with EFCore store at the moment in the preview, you might want to look at it anyway. I hope to get the final release out soon.

**Comment by dwt12777** [comment]
Thank you very much for the response and encouragement.  I'll dig in!

Quick question regarding:

> A regular app that uses the multitenant store basically is read-only from it during tenant resolution. However a backend "admin" or maintenance app needs to populate the store. Each type of store can have its own way to do it -- ultimately if you are using a SQL Server database as the mlutitenant store all you need to do is insert the appropriate data into the tables.

What tables/schema do I need to build?  Just something to hold the TenantInfo objects with fields for each of the tenantinfo properties?  Or are there other tables the library requires before it'll work?  I get the feeling that's kind of up to me, as long as I have the calls return what the library is expecting... but I'm not sure what that is.  That make sense?

**Comment by AndrewTriesToCode** [comment]
@dwt12777 

It really depends. If I use the EFCore store then I choose to rely on Entity Framework Core to create the tables via migration. You could do it manually in SQL Server with CREATE and INSERT statements and implement a simple `IMultitenantStore` to query your custom database without using EFCore at all.

**Comment by dwt12777** [comment]
Makes perfect sense, thank you!
