### ISSUE TITLE
Multi Tenant Users, Same domain, Single login

### ISSUE THREAD

**Issue by TheFoxInSocks** [Finbuckle/Finbuckle.MultiTenant#308]
Hello,

I have a use case where I am trying to create a multi-tenant system, however I want to use a single domain and have have all users go through the same login screen.

Scenario one:

Client registers for our app and a route is created for them (example.com/tenant1). He can then add new users to the account within the app.

Scenario two:

Support receives an issue on a specific tenant (example.com/tenant1), and needs to login to that tenant. The support user is associated with the master tenant as well. Currently, you need to create the support user in each tenant leading to duplicate records in the AspNetUsers table. 

Is there a way to use a tenant-to-user mapping table so that when the user logs in, he is presented a list of tenants he is associated with, all while using the same domain? Then the user can select the tenant he wishes to access and  Finbuckle will set that as the selected tenant.

Thank you in advance!

**Comment by AndrewTriesToCode** [comment]
Hi @Stephen250 

Have you seen the shared login sample? It's only ASP.NET Core 2.1 but the idea should carry forward.

That should cover the regular user sign in, but as you have seen the sys admin signin for any tenant is trickier.

The most practical solution I've seen is to ignore the built-in tenant filter on EF queries on sys admin pages. This is made more difficult because it means you can't use some of Identities methods. I should probably write some extension methods for Identity to help make this easier.

An alternative is to use the `TrySetTenantInfo` on `HttpContext` (make sure to use the option to reset the DI scope), to change to the desired tenant, sign in the user, then redirect as needed. This will force the cookie options to get regenerated under the new tenant when signing in the user so that in the redirect the correct cookie is used. If you are using subdomains for each tenant this can be trickier but is possible.

Another options is to not use per-tenant Identity, but have each user in regular a Identity database associated with one or more tenants. Most identity users would only associate to a single tenant, but the sys admins could associate to many or all. This has its own set of complications but can work well.

See if that gets you any further and let me know what sorts of issues you hit up against.

**Comment by TheFoxInSocks** [comment]
@AndrewTriesToCode yes, I took a quick skim through the shared login example and would like to go that route with having the tenant as the first route (example.com/tenant)

I'm still a little confused with the multi tenant on a shared login within a single domain side of it...

If I am creating the system admin user for each of the tenants, when I go to login via the shared login, Identity will pick up that there is multiple users that exist, therefore how does it know which one to choose?

In the case of the shared login example, I think there would have to be a mapping table, tenant to user. 

Within the DB you would only have the one user account with a currentTenantId (to not confuse identity), then you can present a list of Tenants that user is associated with. Once the user selects a tenant it updates the currentTenantId and sets the TenantInfo to that tenant.

Is this currently possible or can be easily configured?

**Comment by TheFoxInSocks** [comment]
Hello @AndrewTriesToCode, 

After further review would it be possible to utilize a shard Multi Tenant DB Approach?

For Example, we have 3 Partners (A, B, C) that need their Clients within their tenant:

- Partner A has there tenant with multi accounts set up.
- Partner B has there tenant with multi accounts set up.
- Partner C has there tenant with multi accounts set up.

My thought based on the framework was that I would have a global Identity DB (Shared Login Example, Catalog) that would be linked to a Partner DB. Within the Partner DB they would have their accounts which could have many users tied to the account.

When the user signs in, it would set the connection string to the Partner database, then the tenant identifier would be used on the tables to filter the data.

By default, I would set the Strategy as static and determine the Tenant once they are logged in.

In addition, with the PR #309 if a user is tied to multiple tenants, I can present them with a list of tenants and change the active client based on their selection.

I wanted to check with you if this was possible before implementing in my code base.

**Comment by AndrewTriesToCode** [comment]
hi @Stephen250  sorry for the late reply

I think what you described can work. It will be tricky no matter what approach you take. Let me ask some questions to better understand:

0. Are you saying each partner has its own set of tenants under it?

1. In your scenario would a user ever need to be shared across the three partners or can you assume each partner is "isolated"?

2. If each partner is isolated, do the users within belong to only a single tenant or could they be part of multiple tenants within that partner?

**Comment by TheFoxInSocks** [comment]
Hi @AndrewTriesToCode, No Worries!

0.  Ideally I would have a Catalog DB that houses all the Identity and global entitles for all the tenants.  The Partner DB would contain the Tenant Specific Tables and could be used either of the two ways:

- A partner buys in to our system, and wants its clients (multi-tenants) within that database.
- A partner buys a special subscription that keeps their data in an isolated database (one tenant)

1. Right now it would be just the support account that would require access to multiple partners, however each partner could offer different products and we might get some cross over long term.

2. As for now I only foresee crossover for the support account.
