### ISSUE TITLE
Data Sharing Between Tenants

### ISSUE THREAD

**Issue by navneet10sep** [Finbuckle/Finbuckle.MultiTenant#344]
Is it possible to share the data between two or more tenants? I have a scenario where one user can manage two companies, each company can have its own database. The database can be on the same or different SQL servers.   I am looking for a solution where under one DB context I can read/write the data for multiple tenants

**Comment by AndrewTriesToCode** [comment]
Hi @navneet10sep 

Yes, the library can handle this transparently via `IMultiTenantDbContext` and/or `MultiTenantDbContext`. These use a global query filter internally to filter on the current tenant. It works well for most situations but global query filters do have their limitations.

I'm happy to help but first let me refer you to two specific resources:
- the [data isolation docs](https://www.finbuckle.com/MultiTenant/Docs/EFCore) lays out the details. If you are doing a hybrid approach where some tenants have their own database and others have a shared one you can basically use the shared database model but with different connection strings for the tenants. Tenants that have their own database will have some overhead due to the global query filter which technically isn't needed since they are the only tenant in the db... but the overhead isn't usually noticable and it lets you code your app the same for all tenants.
- the [data isolation sample project](https://github.com/Finbuckle/Finbuckle.MultiTenant/tree/develop/samples/ASP.NET%20Core%203/DataIsolationSample) shows an implementation of a hybrid scenario -- 1 tenant has its own database and 2 use a shared database.
