### ISSUE TITLE
Struggling to inject a populated ITenantInfo into DbContext

### ISSUE THREAD

**Issue by white-label-development** [Finbuckle/Finbuckle.MultiTenant#366]
Hi,

I'm using a Configuration store with a custom ITenantInfo, which works in an MVC controller as per your examples

```
IxxTenantInfo ti = HttpContext.GetMultiTenantContext<xxTenantInfo>()?.TenantInfo;
```

I'm using a 'Clean Architecture' approach, and struggling to get tenant information into my DbContext in the Application layer.

DI is injecting objects but they have no values (all are null), eg:

```
services.AddScoped<xxTenantInfo>();
services.AddScoped<IxxTenantInfo, xxTenantInfo>();


// injected classes have null values
public WebDbContext(xxTenantInfo tenantInfo)

// or
public WebDbContext(IxxTenantInfo tenantInfo)
```

The WebDbContext in the Application class library cannot access the `GetMultiTenantContext` extension, even if I inject a HttpContextAccessor and use that.

I understand that it is hard for you to comment on this without the details of my code - but is there anything obvious I should be doing?

**Comment by AndrewTriesToCode** [comment]
hi @white-label-development 
In your clean architecture are you using tenant resolution or do you just want a "static" tenant info so you can get the db context working? Are you also using `services,AddMultiTenant<xxTenantInfo>` in your configuration? It's actually possible to use it without ASP.NET and its baggage if that's what you are trying to achieve.

If you can show a little more of your configuration or even create a sample project that reproduces the issue I'd be happy to take a look.

**Comment by white-label-development** [comment]
Thank you for such a quick reply and thank you so much for this great library. I just moved off Orchard.Core as it was getting in the way. This library does not - you have done a brilliant job.

I have solved my issue - I was being an idiot and should know by now to take a walk before posting for help. Thanks anyway - it's all good here now :)

**Comment by AndrewTriesToCode** [comment]
Excellent!

**Comment by jsonarso** [comment]
@white-label-development @AndrewTriesToCode hey guys, just wanted to comment about this because I'm having some similar issues.

I'm also using Clean Architecture for my project so I have a Infrastructure project where I'm configuring multitenancy as follows (omitting secrets).

![image](https://user-images.githubusercontent.com/73246192/144310686-ba475f97-7f09-44af-9283-f29912a84c00.png)

Then I just called that method in my Startup.cs file to register the services as follows.

![image](https://user-images.githubusercontent.com/73246192/144310886-6796bdeb-29c4-45be-b130-72d7d65bf6b3.png)

The problem that I'm having is that my database context can't be loaded because when trying to set up the connection string it is actually null.

![image](https://user-images.githubusercontent.com/73246192/144311200-0e264359-4bf4-485e-96fc-b3cb561a76ea.png)
![image](https://user-images.githubusercontent.com/73246192/144311217-25eec51b-1039-4747-bea5-0d981cb1ab51.png)

The final goal is to be able to use it with the host strategy so I can use multiple subdomains and match configuration un appSettings files but for know I just wanted to tested in the easiest way.

I'd would appreciate if you guys can give me any advice or comments about how to set this up and make it work. Not pretty sure if this issue should be re-opened but commented here because it was related.

**Comment by AndrewTriesToCode** [comment]
Hi @jason8496as 

Unlike @white-label-development it looks like your app is using ASP.NET Core. In that case does this section of the docs (and the EFCore docs it links to) on design-time instantiation help? [Docs link](https://www.finbuckle.com/MultiTenant/Docs/v6.5.1/EFCore#design-time-instantiation)

Cheers!

**Comment by jsonarso** [comment]
@AndrewTriesToCode that's correct. I'm using .NET Core. 

I found that Deriving from MultiTenantDbContext is an easiest way. Working just as expected.

**Comment by AndrewTriesToCode** [comment]
Glad to hear. If you have any more problems just open up a new issue.
