### ISSUE TITLE
Blazor Web Assembly and .NET 5 Error

### ISSUE THREAD

**Issue by jaltenbernd** [Finbuckle/Finbuckle.MultiTenant#368]
I created a brand new .NET 5 Blazor WebAssembly project and installed Finbuckle.MultiTenant.AspNetCore. Unfortunately, I'm getting the following error:

`
Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1082	There was no runtime pack for Microsoft.AspNetCore.App available for the specified RuntimeIdentifier 'browser-wasm'.	DLR.Bold	C:\Program Files\dotnet\sdk\5.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets	387	
`

**Comment by AndrewTriesToCode** [comment]
@jaltenbernd thanks for reporting the issue. I'll start taking a look. Did you find any way around the error?

**Comment by jaltenbernd** [comment]
> @jaltenbernd thanks for reporting the issue. I'll start taking a look. Did you find any way around the error?

No. I tried Blazor Server instead. But, really couldn't get that working when trying to use the route style: http://contoso.com/abc and http://contoso.com/xyz. I think the sub-domain routing will work, but trying to figure out if I could use the folder route instead.

**Comment by AndrewTriesToCode** [comment]
@jaltenbernd a few more questions, are you using Finbuckle.MultiTenant 6.1? If so can you see if a .NET Core 3.1 app has the same error?

**Comment by AndrewTriesToCode** [comment]
Just following up here. I think since Blazor has its own routing system separate from ASP.NET Core it's safe to say that router based tenant resolution for Blazor is only supported currently against the initial URL that triggers the start of Blazor which is usually at the root and so not that helpful. I will investigate possible solutions for Blazor routing.
