### ISSUE TITLE
Configure multiple Open ID Connect schemes for a single tenant

### ISSUE THREAD

**Issue by ztam** [Finbuckle/Finbuckle.MultiTenant#399]
Hi!

I'm having problems figuring out how to configure multiple OIDC schemas pr tenant.

I have a use case where a tenant is required to have two different OIDC schemas. I can configure one by using WithPerTenantOptions<OpenIdConnectOptions>, but I can't find a way to do this for both.

Is this supported by the library or do I have to solve this some other way?

**Comment by AndrewTriesToCode** [comment]
hi @ztam there isn't any specific support for multiple schemas per-tenant. In your case is it a single database where the schema separates per-tenant data or is it a situation where each tenant needs multiple tenants?

**Comment by ztam** [comment]
Thanks for your reply.

I think this got a bit lost in translation. I have updated the heading to hopefully clarify a bit, sorry about that!
My issue is to configure two different OpenID Connect authentication schemes for the same tenant. :)

**Comment by AndrewTriesToCode** [comment]
Ah Ok, I was thinking database schemas... but I see what you mean now. You can of course register 2 schemas with separate per-tenant options so that they are configured as needed for that tenant. The caveat is that it'll see those 2 schemas for all tenants and not just for the one you want. You also would have to tell ASP.NET Core which one to use "manually" when you call `AuthenticateAsync` by providing the tenant name.

With the change to authentication schemes in ASP.NET Core 2 the commonly recommended approach to multi tenant was a scheme per-tenant, but I decided I didn't like that and thus create this library :) Before that the common approach was separate pipelines/middleware per-tenant but the new scheme based authentication didn't work well with that approach. I settled on the approach with the normal single schemes and per-tenant options to control the behavior.

I would say do what works for your use case though. This library is still good for other aspects of multitenant e.g. tenant resolution and other per-tenant options. You could simply have a list property on the `TenantInfo` listing all the valid schemes for that tenant -- and you might only have 1 or 2 tenants that have more than a single value there. I believe different schemes of the same auth type differentiate their options in ASP.NET Core via named option where the option name matches the scheme name. Finbuckle will adjust all options created of a registered type, regardless of the option name so you have to be careful. It would be a good enhancement for it to better support named options.

I hope that makes sense and please let me know how it goes.

**Comment by ztam** [comment]
Sorry for the late reply, I was suddenly thrown into a new project...

It seems to me that I have to figure out another way to handle this problem as both schemes use OpenIdConnectOptions and this library does not support named options yet.

Thanks for the input, still loving this lib :)
