### ISSUE TITLE
Hybrid Per-tenant and Shared Database Help

### ISSUE THREAD

**Issue by TheFoxInSocks** [Finbuckle/Finbuckle.MultiTenant#400]
Hello @AndrewTriesToCode,

Love the repo, it has saved me tons of time with integrating multi-tenancy in my application.

**What I am trying to achieve:**
- I have a hybrid setup where I have Partners (Tenancy Level 1, 3 Databases) ->  Subscribers (Tenancy Level 2, Many Tenants within DBs)
- The Partners want their subscribers kept independent of the other partners.

**Current Site Setup (HostStrategy):**
- app.site.com (maps to Partner 1 Database Separate DB)
- demo.site.com (maps to Partner 2 Database Separate DB)

When signing in to the app, I want to check the Partner DB for the Client and set it to that TenantInfo:
- Client 1 (TenantInfo1 within partner 1)
- Client 2 (TenantInfo2 within partner 1)
- Client 3 (TenantInfo3 within partner 2)
- Client 4 (TenantInfo4 within partner 2)

**Example:**
1. Go to app.site.com (Pulls Partner 1 DB connection String based on HostStrategy)
2. Login as Client 1 (Sets the TenantInfo on login to the new TenantInfo)

**Restrictions:**
- My App is currently hosted in an Azure app service and does not change from Partner to Partner. 
- Unfortunately, I only have 5 slots so Ideally I would want to create a new url to point at that slot. 

Do you have a suggestion as to how I can achieve this with Finbuckle?

Thank you in advance.

**Comment by AndrewTriesToCode** [comment]
@Stephen250 
thanks for the question and your details. I will take a look shortly.

**Comment by AndrewTriesToCode** [comment]
@Stephen250 Sorry for the delay getting back to you

I think this is doable if you use the `ClaimStrategy` to capture the tenant for a logged in user/client followed by the `HostStrategy` to handle users not logged in.

It would look something like:
```
services.AddMultiTenant<MyTenantInfo>.WithClaimStrategy().WithHostStrategy()...
```
`ClaimStrategy` will look for a user claim named `__tenant__` (by default) and use that to derive the tenant. As an example, in ASP.Net Core Identity you can store the claim for a user in the database and it will add those claims to the sign-in cookie automatically. Take a look at the [ClaimStrategy sample](https://github.com/Finbuckle/Finbuckle.MultiTenant/blob/main/samples/ASP.NET%20Core%203/ClaimStrategySample/Startup.cs) to see how this works. (now that I look at it that same needs some improvement, hopefully what I said makes sense)

If nobody is logged in it will try the next registered strategy, the `HostStrategy` in this case, so that the proper signin database can be used.

One caveat here is the tenant store. You could register separate stores, one for the partners and one for the "subtenants" and it will search them in term -- be careful because by default some of the stores are singletons so it's not straightforward to have separate instances. I'd probably just go with a single store that has them all in there together as "equals" as far as Finbuckle.MultiTenant is concerned.

Please let me know how it goes.

Cheers,
Andrew

**Comment by TheFoxInSocks** [comment]
@AndrewTriesToCode Sorry for the late reply.

Finally got around to this and it works like a treat.

Thank you for your help.
