### ISSUE TITLE
[Question] GraphQL Hotchocolate (AddPooledDbContextFactory) and Finbuckle

### ISSUE THREAD

**Issue by hbermani** [Finbuckle/Finbuckle.MultiTenant#402]
Hello,

So I am looking at integrating GraphQL into one of my projects that uses Finbuckle and my GraphQL library of choice at this stage is Hot Chocolate . Reading through the HotChocolate docs I notice there is a requirement to add a pooled DbContext Factory., the reasoning for this is 

> "The execution engine of HotChocolate executes resolvers in parallel. This can lead to exceptions because the database context of Entity Framework cannot handle more than one request in parallel....... The execution engine needs more than one database context. You should register the database context in a pool rather than transient. During execution database contexts are taken from this pool and returned once the resolver is completed. This has a smaller memory impact, as creating a new context for each resolver." 

This got me thinking, how do we go about implementing this in a Finbuckle multitenant environment. Particularly, where each HTTP request is instantiating one context. Also should we go down the route of a pooled DbContext, can that be configured in a way that respects multitenancy?

For a bit of background , here is the current implementation code for a functioning multitenant environment.
```
            services.AddMultiTenant()
                .WithStrategy<CustomMultiTenancyStrategy>(ServiceLifetime.Scoped, new object())
                .WithConfigurationStore( Configuration, "Finbuckle");

            services.AddDbContext<XContext>();
```

Below the recommended code in the docs to replace  services.AddDbContext line , but would it take into account multitenancy
```
services.AddPooledDbContextFactory<XContext>(b => b /*your configuration */)
```

This code from XContext might also be handy 
```
       protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseLazyLoadingProxies(false);
            optionsBuilder.UseSqlServer(ConnectionString, options => options.EnableRetryOnFailure(
                    maxRetryCount: 10,
                    maxRetryDelay: TimeSpan.FromSeconds(30),
                    errorNumbersToAdd: null
                ));
          

            base.OnConfiguring(optionsBuilder);
        }
```

Link to Hot Chocolate docs:
  https://chillicream.com/docs/hotchocolate/integrations/entity-framework/

**Comment by natelaff** [comment]
Funny, this is the same reason I am interested in #375 too. The only way to know is to try it. I haven't had time to look into this yet.

**Comment by AndrewTriesToCode** [comment]
Hi @hbermani thanks for the question. I need to learn more about GraphQL in general, but with respect to the db context pool I have an idea.

So here is something to test out. It's on my list but I just don't have all the time I wish I did to get to it all.

In theory instead of passing `ITenantInfo` or an implementation to a db context you could pass `IMultiTenantContextAccessor<T>` (or the non generic version), accessor the `MultiTenantContext` and the `TenantInfo` to get the connection info. This uses an `AsyncLocal<T>` variable to access the `MultiTenantContext` similar to how `HttpContextAccessor` works.

So that might let you get around the problem of a db context being stuck with the `ITenantInfo` it was constructed with. What I don't know is if it's possible to change the connection string for the context after `OnConfiguring` has been called. I'm pretty sure, but not 100%, that `OnConfiguring` would only get called once initially for a pooled db context. I would think it should be doable I just haven't looked into it. What do you guys think?

**Comment by natelaff** [comment]
@hbermani did you try this yet? I haven't had time myself but am curious on the results.

**Comment by hbermani** [comment]
Hi @natelaff , I ended up using OData instead of GraphQL... seems to do the job for now.

**Comment by g-6k** [comment]
Hello, any news her ? Really need to use PooledDbContext ?

**Comment by AndrewTriesToCode** [comment]
@g-6k not at the moment but since I think it should be straight forward I will prioritize it. See my comment above for an approach using `IMultiTenantAccessor` injected into the db context instead of the current tenant provides a possible workaround.
