### ISSUE TITLE
Which Strategy for Single Sign On?

### ISSUE THREAD

**Issue by jaltenbernd** [Finbuckle/Finbuckle.MultiTenant#403]
I setup Finbuckle for a client and it's working just fine for the past 6 months. Now, they come to me asking they have a tenant that wants to automatically sign in to the Site. Their tenant has an Intranet and when a User logs in they want to click on a button or link to come over to my client's site without logging in again. 

I know this is in the realm of single-sign-on, OpenId, and Oauth2. But, would that be adding a different "strategy" in Finbuckle? If so, how?

**Comment by AndrewTriesToCode** [comment]
hi @jaltenbernd 

The tenant strategy to resolve the tenant wouldn't change. Instead using per-tenant options we'd change their default `ChallengeScheme` to use the open id connect scheme (or OAuth or whatever) and per-tenant options to set the opened connect options.

Take a look at the [per-tenant authentication sample](https://github.com/Finbuckle/Finbuckle.MultiTenant/tree/main/samples/ASP.NET%20Core%203/PerTenantAuthenticationSample). This uses the [configuration conventions](https://www.finbuckle.com/MultiTenant/Docs/Authentication#using-withpertenantauthentication) to set the options accordingly -- it's basically just per-tenant options based on preset property names.

In the sample you can look at the `appsettings.json` file to see how each tenant has different openid connect settings.  The "megacorp" tenant is set to use the "cookies" challenge scheme but the other sample tenants have the open id connect scheme shown and its related options. The specific scheme names might be different in your app -- ASP.NET Core Identity tends to change the names internally.

I hope this helps. It's not the easiest thing because SSO is complicated by itself not even taking into account how ASP.NET Core does it in additional to how Finbuckle works. If you hit any specific issues please let me know. I am also available for consulting if you'd like to consider that option.

**Comment by jaltenbernd** [comment]
You'll love this. Now, they want only "one" account per school to access the Site instead of individual teacher accounts. Can I still do this within Finbuckle where I have each school have one access token of some sort to access their section?

**Comment by AndrewTriesToCode** [comment]
@jaltenbernd clients are fun like that :)

Finbuckle can still handle this and will help if you need different authentication or app options for each tenant. If the functionality is basically the same for all tenants though you might just go with a regular app with a normal user system. Do you think it's possible they would ever change their mind back to their original request?
