### ISSUE TITLE
Setting default values when using .WithEFCoreStore

### ISSUE THREAD

**Issue by devalot76** [Finbuckle/Finbuckle.MultiTenant#406]
Hi,
I've switched from .WithConfigurationStore to .WithEFCoreStore and now I'm wondering how to set the default values for the tenant like those in the appsettings.json file:

"Finbuckle:MultiTenant:Stores:ConfigurationStore": {
	"Defaults": {
	  "ConnectionString": "server=localhost;....",
	  "CookiePath": "/__tenant__",
	  "CookieLoginPath": "/__tenant__/Identity/Account/Login",
	  "CookieLogoutPath": "/__tenant__/Identity/Account/Logout",
	  "CookieAccessDeniedPath": "/__tenant__/Identity/Account/AcceDenied"
	}

Thank you.

**Comment by AndrewTriesToCode** [comment]
hi @devalot76 
Good question -- don't have an equivalent for the other store. Since the database behind EFCore can vary so much it's kind of hard to prescribe a universal approach. I'm open to ideas and interested in any workaround you might have.

One idea is to make a custom `IMultiTenantStore<T>` that wraps another store that holds default values and presets them on any tenant info it pulls from the wrapped store.

In fact this might be something we can include under the hood and have default values that work for all store types.

**Comment by AndrewTriesToCode** [comment]
Looking into this I think the best option is to stick to EFCore functionality. See the [default value docs](https://docs.microsoft.com/en-us/ef/core/modeling/generated-properties?tabs=data-annotations#default-values) in the EFCore docs. Thanks for raising the question!

**Comment by VictorioBerra** [comment]
@AndrewTriesToCode

Could this be achieved by using multi-stores, IE: WithConfigurationStore  + WithEFCoreStore?

**Comment by AndrewTriesToCode** [comment]
> Could this be achieved by using multi-stores, IE: WithConfigurationStore + WithEFCoreStore?
I don't think so because it'll use the entire value from the first match it finds in a store.

This is a tricky one and I don't have a standard answer.
