### ISSUE TITLE
To fast logout

### ISSUE THREAD

**Issue by szymczakk** [Finbuckle/Finbuckle.MultiTenant#415]
Hi, I have a project in .net 3.1 with Finbucke.MultiTenant 6.2.0. 

When a user logs in he is automatically logged out in +- 1h but I want to keep the session for 12h or even longer. How can I achieve that?

My code for MultITenant configuration

```
 services.AddMultiTenant<TenantInfo>().WithHostStrategy()
.WithStore<MultitenantAzureStorageStore>(ServiceLifetime.Scoped) //my own implemented store
.WithPerTenantOptions<CookieAuthenticationOptions>((o, tenantInfo) =>
{
    o.Cookie.Name = "FC.SigninCookie." + tenantInfo.Name;
    o.ExpireTimeSpan = TimeSpan.FromHours(12);
    o.SlidingExpiration = true;
})
.WithPerTenantAuthentication();
```

What am I doing wrong?

Thanks for your help,
Cris

**Comment by AndrewTriesToCode** [comment]
hi @szymczakk sorry for the slow reply

I'm not sure what would be causing it. If you check the browser dev mode what lifetime does it show for the auth cookie when it is first created?

I'm happy to take a closer look -- is there a repo I can access to see an example application where this is occurring?

**Comment by szymczakk** [comment]
Hi, not a problem,

I will prepare one later. 

As a quick fix I deleted `WithPerTenantAuthentication` and it's working right now.

**Comment by AndrewTriesToCode** [comment]
@szymczakk a few questions
- are you using identity?
- in your call to `SignInAsync` are you setting the `IsPersistant` property to `true`?

I suspect that `WithPerTenantAuthentication` conflicted with the prior call to `WithPerTenantOptions` -- something I need to investigate

**Comment by szymczakk** [comment]
Hi,

yes Im using Identity and Im setting it to true.

I will prepare test repo for you where you will be able to investigate it ;)

wt., 13 kwi 2021, 07:21 użytkownik Andrew White ***@***.***>
napisał:

**Comment by AndrewTriesToCode** [comment]
hi @szymczakk 
Just following up here-- did you create a test repo? Sorry if I missed it

**Comment by Nivalux** [comment]
I had a similar problem and after some research found the issue.
When using the .WithPerTenantAuthentication() extension method, it breaks the User Validation, triggered by the validation timeout.

I set it like this:
```cs
services.Configure<SecurityStampValidatorOptions>(options =>
            {
                // This also refreshes the User Claims
                options.ValidationInterval = TimeSpan.FromSeconds(10);
            });
```

What this does is reloading the Claims for the user after the interval passed.
When you use the method `.WithPerTenantAuthentication()`, then it expects the User to have the Claim `__tenant__` with the value of your tenant id. If it does not have it, then the Principal will be rejected.

It works after the first SignIn, because at https://github.com/Finbuckle/Finbuckle.MultiTenant/blob/4c422b3965ff326f3232cfeb7091d44dbe1db006/src/Finbuckle.MultiTenant.AspNetCore/Extensions/MultiTenantBuilderExtensions.cs#L107 it get's set after signing in.

The problem is, that this event does not get triggered after the UserClaims have been loaded again.
To fix it you can add a custom `UserClaimsPrincipalFactory`. I had that anyway, because I needed to add custom Claims to the user. 

```cs
public class UserClaimsFactory : Microsoft.AspNetCore.Identity.UserClaimsPrincipalFactory<Data.Set.User>
    {
        private readonly Common.Tenant _tenant;
        public UserClaimsFactory(UserManager<Data.Set.User> userManager, IOptions<IdentityOptions> optionsAccessor, Common.Tenant tenant) : base(userManager, optionsAccessor)
        {
            _tenant = tenant;
        }

        protected async override Task<ClaimsIdentity> GenerateClaimsAsync(User user)
        {
            var principal = await base.GenerateClaimsAsync(user);

            const string strTenantType = "__tenant__";
            if (_tenant != null)
                principal.AddClaim(new Claim(strTenantType, _tenant.Id));

            return principal;
        }
    }
``` 

and register it in the Startup.cs
```cs
services.AddScoped<IUserClaimsPrincipalFactory<Data.Set.User>, UserClaimsFactory>();
```

After doing that the user always had the tenant claim and did not get rejected at https://github.com/Finbuckle/Finbuckle.MultiTenant/blob/4c422b3965ff326f3232cfeb7091d44dbe1db006/src/Finbuckle.MultiTenant.AspNetCore/Extensions/MultiTenantBuilderExtensions.cs#L90

**Comment by AndrewTriesToCode** [comment]
@Nivalux thanks for the detailed response. I probably need a more robust method of setting the tenant claim -- probably via an `IUserClaimsFactory` that wraps around any preexisting user claims factory. Thanks!

**Comment by AndrewTriesToCode** [comment]
Looking into this and working on a solution. I actually have a tenant claim in my Identity user model so I think it was preventing me from seeing the issue. Hope to have a release with this fix out soon.
