### ISSUE TITLE
Update cache on delegate strategy

### ISSUE THREAD

**Issue by ingleo44** [Finbuckle/Finbuckle.MultiTenant#423]
I am using the Distributed Cache store for my solution but now I am facing a new challenge, my strategy resolution is a delegate strategy which retrieves the tenantId from a claim of the authenticated user but I would like to retrieve the the tenant information from the database in the delegate and then save it in the distributed cache for tenant resolution. Do you have any advice of how I can get this?

**Comment by AndrewTriesToCode** [comment]
Yes -- the last release contained an event sytem. See PR #359 for details. This will let you hook into when a tenant has been retrieved and if it is not in the cache you can add it there so that future requests will find it in the cache.

In this case you would have 2 stores. You'll want to register the distributed cache store first, then the slow database store after. For a request the stores will be checked in the order registered so things in the cache are resolved fast, but it was from the database store then you can add into the cache in the event that is fired.

Let me know how it goes!

**Comment by ingleo44** [comment]
I followed your advice and it worked
