### ISSUE TITLE
Separate identityDb by tenant

### ISSUE THREAD

**Issue by solopromiguel** [Finbuckle/Finbuckle.MultiTenant#437]
It is possible to separate the Identity in another database per tenant.
Thank you

`ApplicationDbContext : MultiTenantIdentityDbContext`

**Comment by AndrewTriesToCode** [comment]
Yes, all you need to do is have each tenant have a connection string to it's own database then in your `DbContext` configuration have it use the connection from the tenant info. Technically you don't even need to use the "MultiTenant" db contexts here since they include functionality intended for shared-database (and hybrid) scenarios.

Take a look at [this part of the docs about separate databases per-tenant.](https://www.finbuckle.com/MultiTenant/Docs/EFCore#separate-databases)
