### ISSUE TITLE
ClaimsStrategy with multiple authentication schemes: Am I doing this right?

### ISSUE THREAD

**Issue by ericmqt** [Finbuckle/Finbuckle.MultiTenant#468]
I was struggling to get Finbuckle.MultiTenant to recognize my OpenIddict access tokens, even though the claims strategy was working fine for my B2C tokens. After barking up several wrong trees and examining the source for `ClaimsStrategy`, I realized this was because that strategy only uses the default authentication scheme (in my case, B2C), so it would happily pull my B2C tenant ID claim but never even see the OpenIddict tokens. 

I created a new `IMultiTenantStrategy` which is basically just a modified `ClaimsStrategy` that checks each authentication scheme until it finds the claim, and that finally fixed my issue. 

However, I'm not intimately familiar with the nitty-gritty of authentication in ASP.NET Core and I am very wary of doing something wrong here, since this seems like an excellent place to accidentally introduce a vulnerability! I would very much appreciate if anyone could let me know if I've done this correctly. I'm assuming there was a good reason the original strategy only checked the default scheme, but I don't know if it was for a reason I can safely ignore in my use case.

My questions/concerns:

1) The [source I referenced](https://github.com/Finbuckle/Finbuckle.MultiTenant/blob/960458a4adfe1d862f98e7869bdb4bf52edbd629/src/Finbuckle.MultiTenant.AspNetCore/Strategies/ClaimStrategy.cs#L46) for `ClaimStrategy` does not check the `AuthenticationResult` returned by `AuthenticateAsync()`--is this check skipped intentionally or should I be ensuring the result succeeded before trying to pull my tenant ID claim?

2) Related to the first question, is there any sort of additional validation I should perform on the authenticated principal before pulling my claim? Or is this far enough along in the pipeline that I don't need to worry?

3) I noticed `IAuthenticationHandler.GetRequestHandlerSchemesAsync()` as a potential alternative to `IAuthenticationHandler.GetAllSchemesAsync()`, but in my project `GetRequestHandlerSchemesAsync()` doesn't return any auth schemes, so I'm not sure if this is potentially a better method to use but needs additional configuration, or if `GetAllSchemesAsync()` is fine for my purposes.

4) Do I need to consider a possibility of a specially-crafted request with two valid tokens for different, non-default schemes? e.g. an attacker is an admin in tenant 1, but a regular user in tenant 2, and while logged into tenant 1 supplies a tenant 2 token containing a different tenant ID, tricking my strategy into pulling the tenant ID for tenant 2 and giving admin access to the more restricted tenant 2 resources? Or is that out of scope here? Something about just willy-nilly looping through authentication schemes until I get the claim I want strikes me as having some implicit assumptions that could bite me in the butt. I'm a little paranoid about auth stuff.

```
public class RegisteredSchemesClaimsStrategy : IMultiTenantStrategy
{
    public async Task<string> GetIdentifierAsync(object context)
    {
        var httpContext = context as HttpContext;

        if (httpContext is null)
        {
            return null;
        }

        var schemeProvider = httpContext.RequestServices.GetRequiredService<IAuthenticationSchemeProvider>();

        // Try each registered AuthenticationScheme, starting with the default
        await foreach (var scheme in EnumerateAuthenticationSchemes(schemeProvider))
        {
            var handler = (IAuthenticationHandler)ActivatorUtilities.CreateInstance(
                httpContext.RequestServices, scheme.HandlerType);

            await handler.InitializeAsync(scheme, httpContext).ConfigureAwait(false);

            var handlerResult = await handler.AuthenticateAsync().ConfigureAwait(false);

            // QUESTION: Should I check handlerResult.Succeeded before proceeding?
            var identifierClaim = handlerResult.Principal?.FindFirst("tenantId");

            if (identifierClaim != null)
            {
                return identifierClaim.Value;
            }
        }

        return null;
    }

    /// <summary>
    /// Enumerate registered authentication schemes and associated handlers, beginning with the default scheme.
    /// </summary>
    private static async IAsyncEnumerable<AuthenticationScheme> EnumerateAuthenticationSchemes(
        IAuthenticationSchemeProvider authenticationSchemeProvider,
        [EnumeratorCancellation] CancellationToken cancellationToken = default)
    {
        if (authenticationSchemeProvider is null)
        {
            throw new ArgumentNullException(nameof(authenticationSchemeProvider));
        }

        if (cancellationToken.IsCancellationRequested)
        {
            yield break;
        }

        // Yield the default scheme first
        var defaultScheme = await authenticationSchemeProvider.GetDefaultAuthenticateSchemeAsync().ConfigureAwait(false);
        yield return defaultScheme;

        // Yield remaining schemes
        var allSchemes = await authenticationSchemeProvider.GetAllSchemesAsync().ConfigureAwait(false);

        foreach (var scheme in allSchemes.Where(
            x => !string.Equals(x.Name, defaultScheme.Name, StringComparison.Ordinal)))
        {
            if (cancellationToken.IsCancellationRequested)
            {
                yield break;
            }

            yield return scheme;
        }
    }
}
```

**Comment by AndrewTriesToCode** [comment]
hi, thanks for the detailed question. I will take a closer look and get you some answers today

**Comment by AndrewTriesToCode** [comment]
> that strategy only uses the default authentication scheme

This is just because I was short sighted. There is a current PR that among other things lets you tell it what scheme you want it to use. I think you should probably try something like that rather than looping through all the schemes. I will eventually get this added into the library.

1. > The source I referenced for ClaimStrategy does not check the AuthenticationResult

This is by design. The strategy is meant only to extract a tenant identifier from a claim and not to actually perform authentication.

2. > is there any sort of additional validation I should perform on the authenticated principal 

Depends on your use case, but the _real_ authentication validation is handled in `UseAuthentication()`. In the `ClaimStrategy` you'll see I set a bypass for validation which the wrapper validation it puts in place around yours will skip yours -- this is because sometimes validation needs to know the tenant (e.g. for a database call) and at this point we are trying to resolve the tenant so such validation fails. So the idea with this strategy is just to grab a claim from the cookie but not actual do the user authentication -- that comes later with the authentication middleware. It is smart enough not to have to reparse the entire cookie during the actual authentication. If you want to do additional validate look into the `OnValidate` (or something like that) event on the options for your authentication scheme.

3. > `IAuthenticationHandler.GetRequestHandlerSchemesAsync()` as a potential alternative to `IAuthenticationHandler.GetAllSchemesAsync()`

Do you mean `IAuthenticationSchemeProvider`?

A request handler is one that can provide an immediate response to a request (implements `IAuthenticationRequestHandler` instead of just `IAuthenticationHandler`-- like the OpenId Connect handler which handles the a callback from the identity service then redirects the user. This will only [return schemes with such a handler](https://github.com/dotnet/aspnetcore/blob/8b30d862de6c9146f466061d51aa3f1414ee2337/src/Http/Authentication.Core/src/AuthenticationSchemeProvider.cs#L149)

4. > Do I need to consider a possibility of a specially-crafted request with two valid tokens for different, non-default schemes? 

If you use `WithPerTenantAuthentication` the library adds extra authentication that encodes the tenant into the authentication properties which ASP.NET encodes into its tokens. On subsequent authentication the tenant that was encoded into the authentication properties is compared to the current detected tenant and if they don't match it rejects the authentication. Note that the current tenant could be from the claims strategy or from some other strategy. It just makes sure it matches the encoded tenant from the time of token creation. If your tokens are not created in ASP.NET Core this might cause you some issues. Your specific use case might warrant skipping `WithPerTenantAuthentication` and instead using your own `OnValidate` event handling for the scheme.

`WithPerTenantAuthentication`'s validation was more meant for cookie scenarios. Sounds like you might be dealing with APIs / tokens? I'd suggest that if the token is signed (and you trust the provider) you can probably trust it for that single request in terms of the tenant in the claim. You would just want to make sure all authorization is derived from only that token for the request.

Thanks for the tough questions!

**Comment by ericmqt** [comment]
Awesome, thanks for the detailed reply! That definitely clears up a lot.

>There is a current PR that among other things lets you tell it what scheme you want it to use. I think you should probably try something like that rather than looping through all the schemes. I will eventually get this added into the library.

Yeah this occurred to me after the fact... whoops. Because I only ever have the two schemes it probably does not matter from a functional perspective, but I can certainly cut out the overhead of enumeration.

>In the ClaimStrategy you'll see I set a bypass for validation which the wrapper validation it puts in place around yours will skip yours

Are you referring to this line?

```
httpContext.Items[$"{Constants.TenantToken}__bypass_validate_principle__"] = "true"; // Value doesn't matter.
```

I had wondered about that, because I couldn't find any other reference to `__bypass_validate_principle__` in the source code. Should I add that pair of lines verbatim to my handler? It's not clear to me the significance of that key name, and I took "principle" to be a misspelling of "principal" so I assumed it was *probably* not a magic value in ASP.NET Core and something internal to Finbuckle. Or is it simply the setting of *any* key in the context that is desired here? I'm struggling to parse out what you mean

>Note that the current tenant could be from the claims strategy or from some other strategy. It just makes sure it matches the encoded tenant from the time of token creation. If your tokens are not created in ASP.NET Core this might cause you some issues.

To be clear, I'm not using `WithPerTenantAuthentication`. I have two authentication schemes because Azure B2C doesn't support the client credentials flow, so I augmented my identity service with OpenIddict. Azure B2C calls back into my identity service through IEF for things like getting user tenants for sign-in pages, adding tenant ID to tokens, etc., so even though my identity service is *involved* in user authentication, from the server app perspective it is authenticating directly against B2C which of course is a different server/authority than my identity service which issues the OpenIddict tokens, hence the need for two separate authentication schemes (I'm not sure if it's possible to place B2C *behind* my identity service, but for now it seems unnecessary). All of that being said, I'm assuming then because I'm not using `WithPerTenantAuthentication` that the quoted note above does not apply?

Anyways, I don't want to put you out too much chasing this down, you've been very helpful and I'm feeling confident! *HUGE* thanks for this library, it has been a massive help!

**Comment by AndrewTriesToCode** [comment]
Hi!

`principle` -> `principal` I am so embarrassed! Fixed it just now.

So a few updates. I just released 6.4.0 which adds the ability to tell `ClaimStrategy` which scheme it should use. Upon review I realized it only bypassed cookie principal validation if used in combination with `WithPerTenantAuthentication` so I fixed it to bypass regardless.

If you are using the new `ClaimStrategy` you should be able to use it as-is to pull a tenant claim from the given auth scheme, and if it's a cookie based scheme it will skip the principal validation (the real authentication step will still validate). I recommend you place `UseMultiTenant` before `UseAuthentication` in your app pipeline.

I'm glad you like the library. Please considering becoming a sponsor when your app goes viral 😉

**Comment by ericmqt** [comment]
Thanks for all the help, I've really appreciated it! I'll update my packages accordingly.

I've arranged for us to sponsor the project, so greetings on behalf of Dataccuity! We're tiny but we're happy to chip in :)

**Comment by AndrewTriesToCode** [comment]
Thanks! I'm glad to help and I appreciate the support from Dataccuity!

**Comment by stonesvillage** [comment]
> Hi!
> 
> `principle` -> `principal` I am so embarrassed! Fixed it just now.
> 

Hello!

Was this ever fixed? Cannot see the fix in source code.

In ClaimStrategy.GetIdentifierAsync:
`httpContext.Items[$"{Constants.TenantToken}__bypass_validate_principle__"] = "true"; // Value doesn't matter.`

In FinbuckleMultiTenantBuilderExtensions.WithPerTenantAuthenticationConventions
`if(context.HttpContext.Items.Keys.Contains($"{Constants.TenantToken}__bypass_validate_principal__"))`

Notice the difference in spelling "principal".

**Comment by AndrewTriesToCode** [comment]
@stonesvillage yep you are right I missed that! I also realize that I don't have any unit tests for ClaimStrategy because its tough to mock HttpContext, but I'll have to add something at least.

Anyway 6.5.1 fixes it and I will have it up to NuGet.org in a few minutes.

**Comment by stonesvillage** [comment]
Great, thank you!
