### ISSUE TITLE
Question: Is it possible to have a strategy that uses posted name and password only

### ISSUE THREAD

**Issue by iang0ld** [Finbuckle/Finbuckle.MultiTenant#540]
We would like this logic as a strategy.  If name and password provided and nothing else then set a default tenantid from a database, otherwise use claims, otherwise use the url, etc...  I think this may be possible using a custom strategy but I can't find any complete examples?

**Comment by AndrewTriesToCode** [comment]
I know you closed this and are looking at a custom strategy, but I just wanted to say this is possible. I recommend using the claim strategy along with `WithPerTenantAuthentication`. In this case your user database won't itself be multitenant because you won't know the correct tenant until they have signed in.

Let me know if you have any questions here. I'll try to get sample project to show this.

**Comment by iang0ld** [comment]
I’m not sure we need that level of complexity.

Another question though…

It appears that calling the following is checks against the tenantId.  Is that correct?

_userManager.FindByEmailAsync(request.Email.Trim().Normalize());

**Comment by VictorioBerra** [comment]
> It appears that calling the following is checks against the tenantId.  Is that correct?

- You can use SQL Server Profiler and see the queries (start a new profile, and use the duration template)
- You can enable [EF Core simple logging](https://docs.microsoft.com/en-us/ef/core/logging-events-diagnostics/#simple-logging) (this is for 5+) see below!
- You can use miniprofiler (super awesome package BTW) https://miniprofiler.com/dotnet/AspDotNetCore


## EF Core Simple Logging
```csharp
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
{
    optionsBuilder.LogTo(Console.WriteLine);
}
```

I cloned the source code here, and added `_userManager.FindByEmailAsync(...)` in the _LoginPartial (because the _userManager was already there and ready to go).

![image](https://user-images.githubusercontent.com/2934507/156593886-f0f90144-2907-488c-bd93-d2ea163401d5.png)

You can see tenant filter is used everywhere.

@iang0ld Don't be afraid to look at the source code, and don't be afraid to look at logs especially EF query logs.

**Comment by iang0ld** [comment]
I want a root admin to be able to log into a tenant for maintenance and support purposes.

Do I need to create an admin user for every tenant or is there a way of changing the TenantId, or of ignoring the TenantId when trying to get the user using through say FindByEmailAsync(email). Or is this line of thinking anti multitenant and wrong?

I think this comes under the subject of impersonation.

**Comment by iang0ld** [comment]
I should mention I can to call an endpoint to effect the tenant impersonation. I’m thinking something like ReplaceToken which is similar to refeshtoken but carries the TenantId we want to impersonate. We have tried a few things but they don’t seem to work because the email is always compared to the tenant id of the admi with is always root.

**Comment by iang0ld** [comment]
Thanks for this.  It is a great help, not just for this question but moving forward.

I am desperately trying to implement  impersonation. I want to add an endpoint which checks the user. But I can’t because I can’t integrate with our jwt token code because I can get the user from the userManager.

Is there a way to   run user = _userManager.FindByEmailAsync() or _userManager.FindByIdAsync without checking for the tenant, but only for this special case?

**Comment by iang0ld** [comment]
Don’t’ worry guys. I worked this out. I just now the tenantId in the user table for the root admin in the strategies.

**Comment by AndrewTriesToCode** [comment]
Glad to hear you got it figured out!
