### ISSUE TITLE
Database Performance EFCore issues / ideas / questions

### ISSUE THREAD

**Issue by ThatDeveloper** [Finbuckle/Finbuckle.MultiTenant#545]
Hey there,

I have some  ideas / questions regarding DB performance in efcore.

1.  `Finbuckle.MultiTenant.Internal.Constants.TenantIdMaxLength`
     Could this be not internal so I could set the max length myself? Especially in big databases this has a huge impact. I would like to set this e.x. to 32 instead of 64.

2. Index on `TenantId`
    Could there be an index on `TenantId`? The docs only specify a combination of indexes / keys. I did it like this, but I do not know if this is best-practise: 
    ```
     var entityTypes = builder.Model.GetEntityTypes().Select(c => c.ClrType);
     foreach (var entity in entityTypes)
     {
          var bEntity = builder.Entity(entity);
          bEntity.IsMultiTenant();
          bEntity.HasIndex("TenantId");
     }
    ```

**Comment by AndrewTriesToCode** [comment]
Hi!

1. Hi, for this this can simply override it with a call to `HasMaxLength` after `IsMultiTenant` on the "TenantId' property, which should result in the database migration reflecting the override. 
2. I recommend including adding it to whatever other indexes you have. There is a method chained off `IsMultiTenant()` which will try to do this for you/ See [this part of the docs](https://www.finbuckle.com/MultiTenant/Docs/v6.7.1/EFCore#keys-and-indexes).

Another thing I'd recommend, if you have control of your data models, is to add a string TenantId property on them explicitly so that a shadow property isn't needed -- they add a lot of extra complication under the hood and I've had much better success with indexes if it is explicit.

**Comment by ThatDeveloper** [comment]
Thank you @AndrewTriesToCode!
Further Question: So every table will have the TenantId field, and it will always filter for this. What are the Pros and Cons if I would create a seperate Table to bind a int PK to TenantId and then use that in the tables? In regards to Storage and Performance? Do you have some information on this?

**Comment by AndrewTriesToCode** [comment]
@ThatDeveloper so sorry I never replied to you here. I think there would be minimal perf impact based on what you described. However this library assumes a string for TenantId currently and that is unlikely to change in the near future.
