### ISSUE TITLE
SignOutAsync signs out all tenants

### ISSUE THREAD

**Issue by sigurdhj** [Finbuckle/Finbuckle.MultiTenant#546]
Hi.

I've setup two tenants using WithHostStrategy and WithPerTenantAuthentication. Both tenants are using Cookies as their authentication scheme and both tenants have the same cookie name.

I've noticed that when I sign out of tenant A, I also sign out of tenant B. However I can see that tenant B's cookie is still there, when I restart my application tenant B is logged in straight away.

How can I resolve this?

**Comment by VictorioBerra** [comment]
Both tenants have the same cookie name? If so, SignOutAsync would absolutely sign out both.

Are you using Auth0 by chance?

**Comment by sigurdhj** [comment]
I'm not using Auth0. I've basically just altered the PerTenantAuth sample to use HostStrategy and changed to a custom store.

If I'm supposed to be signed out of tenantA when calling SignOutAsync from tenantB, shouldn't I then be signed out of tenantA even after I restart the application? After the restart I'm still signed out of tenantB, which is what I'm expecting. It's the fact that I'm still signed in to tenantA that's confusing.

**Comment by AndrewTriesToCode** [comment]
Hello, this stuff always gets tricky. If you are using the host strategy then sign out would only be for a single tenant--even 'SignOutAll' because the site can only affect cookies it can see and by default the cookie domain is set to the current domain only. You could change this to override the cookie domain to be the main domain for the app which would share a cookie for all subdomains and you'd get similar behavior to what you first described. 

With any other strategy cookie names and paths come into play as @VictorioBerra pointed out.

Thanks!

**Comment by sigurdhj** [comment]
Thanks for the reply.

Sign out being single tenant is what I want, so that's great. The issue is that I'm being "signed out" of the other tenant aswell. In quotes since I'm still signed in after a restart.

**Comment by AndrewTriesToCode** [comment]
What is the flow after sign out in tenant a? Are they redirected anywhere? If you then go to tenant b's subdomain and they aren't logged in can you tell me if the cookie is still being sent?

And finally, can you try without 'WithPerTenantAuthentication' since with host strategy it doesn't really offer as much value?

**Comment by sigurdhj** [comment]
Well this is embarrassing...

I've spent several hours today trying to figure this out, only now to realize that I should have read the URL more carefully. When signing out from a tenant the client gets sent back to the login page (tenantA.example.com/login?ReturnUrl=%2F). So the application went to the login route and showed the login page, as it should.

!"#¤!"%"#¤!"#!"¤!"#%!

Everything works as expected now. Sorry for wasting everyone's time.
