### ISSUE TITLE
Creating new tenant and applying changes without restart

### ISSUE THREAD

**Issue by Sheko007** [Finbuckle/Finbuckle.MultiTenant#56]
Hi,

Everytime I create a new tenant I have to restart the web application so the startup.cs would run again and the new tenant configuration could be applied.

If I create the tenant without restarting I can't access the new tenant website directly as I have to restart to be able to access it.

here is the code I'm using to create the new tenant.
// give him the code you're using

I tried to go through documentation but couldn't find the solution.

thanks

**Comment by AndrewTriesToCode** [comment]
Hi @Sheko007  I think your code snippet didn't make it into the comment.

Are you using the provided "InMemoryStore"? You should be able to get access to it in a controller via depedency injection into the constructor. Then with the instance you can use the TryAdd method to add a new tenant:

```cs
public class MyController : Controller
{
    private readonly IMultiTenantStore tenantStore;

    MyController(IMultiTenantStore tenantStore)
    {
        this.tenantStore = tenantStore; // save the injected tenant store
    }

    public IActionResult MyAction()
    {
        var newTenant = new TenantContext(......);
        tenantStore.TryAdd(newTenant);
    }
}
```

However when the app restarts of course this tenant will be lost because the store is just an in-memory collection-- You might want to implement your own `IMultiTenantStore` where the `TryAdd` and `GetByIdentifier` methods check a database or some other permanent area. You can use your own implementation by using `WithStore<T>` (where T is your implementation type) instead of `WithInMemoryStore` after `AddMultiTenant`.

We have a feature request for this type of Store, but I haven't been able to work on it yet: Item #26

**Comment by Sheko007** [comment]
Thanks.
Good Work
