### ISSUE TITLE
Per Tenant DependencyInjection  

### ISSUE THREAD

**Issue by scharada** [Finbuckle/Finbuckle.MultiTenant#566]
Autofac has this capability using containers. i was wondering if similar behavior can be implemented in this library.
it would be usefull to load modules that are enabled per tenant .. i.e. a tenant can choose which payment provider to use ... enable or disable a feature.

**Comment by chihabhajji** [comment]
for now you can use WithPerTenantOptions and defining lazy loaded properties on your tenant model that hold those informations, also i think (not sure because i havent implemented this) you can use feature flags
https://marcosflobo.com/2021/04/06/multi-tenant-feature-flag-manager/
https://docs.microsoft.com/en-us/dotnet/architecture/cloud-native/feature-flags

**Comment by AndrewTriesToCode** [comment]
Hi, no current plans to implement per-tenant DI. A design decision early on was to go with a per-tenant Options oriented approach rather than separate DI. I know some have meshed it with autofac DI where the Finbuckle tenant is fed into autofac but I'm not too familiar with it.
