### ISSUE TITLE
Failed Authorization doesn't redirect to tenant's login page

### ISSUE THREAD

**Issue by clinically-au** [Finbuckle/Finbuckle.MultiTenant#78]

**Comment by clinically-au** [comment]
Hi.
Thanks for this awesome project!
I am exploring the v2.0.0 samples, specifically IdentityDataIsolationSample.
I've added a Test view & controller, and added the [Authorize] attribute.

If the user is not currently logged in, it does not redirect to the URL set by options.LoginPath in CookieAuthenticationOptions ($"/{tenantInfo.Identifier}/Home/Login").

Instead, it redirects to /Identity/Account/Login, without the tenant Id. 

I can't work out why it is not redirecting appropriately. 

Also, shouldn't options.LoginPath be $"/{tenantInfo.Identifier}/Identity/Account/Login"?

**Comment by AndrewTriesToCode** [comment]
Hi @wojtj 
Thanks for reporting this issue. I was in a rush and that sample was the last thing I updated--looks like I was too much in a rush.

I was able to reproduce the problem--I will try to work out a solution soon. I also see I forgot to add `WithRemoteAuthentication` but that is not related. Thanks again.

**Comment by AndrewTriesToCode** [comment]
@wojtj I was able to nail it down to Identity overwriting our cookie login value. It turns out this only happens with `AddDefaultIdentity` but not with `AddIdentity`. I found this issue just recently reported here:
https://github.com/aspnet/Identity/issues/2019
As you can see I commented and I encourage you to do the same.

As a workaround you can add a call like this after `AddDefaultIdentity`:
```
services.PostConfigure<CookieAuthenticationOptions>(IdentityConstants.ApplicationScheme, options =>
            {
                // This will result in a path of /_tenant_/Identity/Account/Login
                options.LoginPath = $"{options.Cookie.Path}{options.LoginPath}";
            });
```
This assume you've set the cookie path like this earlier:
```
.WithPerTenantOptions<CookieAuthenticationOptions>((options, tenantInfo) =>
                {
                    // Since we are using the route strategy configure each tenant
                    // to have a different cookie name and adjust the paths.
                    options.Cookie.Name = $"{tenantInfo.Id}_{options.Cookie.Name}";
                    //options.LoginPath = $"/{tenantInfo.Identifier}/Home/Login";
                    options.LogoutPath = $"/{tenantInfo.Identifier}";
                    options.Cookie.Path = $"/{tenantInfo.Identifier}";
                });
```

Alternatively you could use a multi tenant strategy that doesn't reply on the path such as the host multi tenant strategy.

Hopefully Microsoft will address the issue linked above so I can publish an updated sample that works.

**Comment by clinically-au** [comment]
Thanks!

Setting the path in services.PostConfigure fixed it.
