### ISSUE TITLE
"Global" login page possible?

### ISSUE THREAD

**Issue by clinically-au** [Finbuckle/Finbuckle.MultiTenant#79]
Hi

I was wondering whether it would be possible to have a generic / global login page for all users, and redirect to the correct tenant for that user **after** login. This would preclude users having to know the tenant name.

In other words, all users login at example.com/Account/Login.
On successful login, redirect to example.com/{tenant-associated-with-user}/Home
?

This would of course require a shared identity DB, and user names would have to be unique across all tenants, but it would be consistent with most multi-tenant apps that I've seen, and be less confusing to new users. 

The alternative of having a landing page listing all tenants is suboptimal (to me), as it advertises who all your customers are.

I'm happy to tinker away if you think it would be possible, but perhaps you can see some structural reasons why it wouldn't work.

Thanks
Wojt.

**Comment by AndrewTriesToCode** [comment]
Hi @wojtj sorry for the late reply.

I haven't tried to build anything like that but I think it could work. It would be sort of like Github where you have an account but can also be part of different orgs.

I think Identity wouldn't interact much with Finbuckle.MultiTenant in this situation. The Identity `User` class would need to somehow track the tenant(s) for each user and redirect them to a proper tenant landing page (and maybe have a way to switch if they are associated to more than one tenant). If you are using the default Identity UI you would need to modify the login page logic to set the `MultiTenantContext` before the login and redirect so that the correct cookie settings are used.

Let me know if you are able to get something working!

**Comment by AndrewTriesToCode** [comment]
Update: I'm going to try to make a sample project for this use case over the holidays. If successful I'll add it to the rest of the project samples.
