### ISSUE TITLE
Reset tenant cache

### ISSUE THREAD

**Issue by chernihiv** [Finbuckle/Finbuckle.MultiTenant#89]
Having set configuration first time (e.g. cookie, oidc, etc), I didn't manage to invalidate it later. Research within existing and closed issues wasn't successful, therefore I decided to create new issue.

Tenant configuration is being changed during period of time: e.g. database connection, OIDC secrets, etc.
Is there any possible way to reset cache for specific tenant?

As enhancement, there should be simple service that could do it.

**Comment by chernihiv** [comment]
I found out how to clear whole cache.

Resolve `IOptionsMonitorCache` using DI, e.g. `IOptionsMonitorCache<TOptions> monitorCache`  where `TOptions` is `OpenIdConnectOptions` in case with OIDC and call Clear `monitorCache.Clear();`

There is `monitorCache.TryRemove("NAME")`, but all items contains unique names, e.g. `2GgPKVmFOyU9O2oTbA+1NLAJI40=oidc`. 
Having passed name as `oidc`, it will remove all caches which belong to `oidc` schema

**Comment by AndrewTriesToCode** [comment]
Hi @chernihiv 

You figured it out! Thanks for replying with your findings so that others can see.

As you saw passing in an option name (without specifying tenant) will remove that named option for all tenants from the cache. the options will get recreated next time they are needed for each tenant. Maybe I should add an API that will let you clear the option for a specific tenant only.

**Comment by chernihiv** [comment]
@achandlerwhite 
It would be great.
I investigated further and figured `MultiTenantOptionsCache` out. It overrides methods of `OptionsCache` and uses `AdjustOptionsName` for name composing. Anyway, it won't work in my case with `TryRemove` if I compose option name using similar algorithm.
Therefore, it would be nice to have option to clear cache only for specific tenant, instead thousands.

Thank you for feedback.

**Comment by chernihiv** [comment]
Hi @achandlerwhite 
Could you say why do we need to hash Tenant ID + Option Name in `MultiTenantOptionsCache`?
The only one thing I come up with is to receive proper Latin symbols (using base64), isn't?

**Comment by AndrewTriesToCode** [comment]
Hi, if we just did tenantid + option name there is potential for conflicts.

Imagine options named "option1" and "ption1" and tenants with ids "tenant1" and "tenant1o". Now suppose you have the tenant id + option name of "tenant1option". Is this tenant1 + option1 or is it tenant1o + ption1. Impossible to say because it matches both. The hash of tenant ID prevents these possible overlaps.

May I ask why you want to directly access the options cache? In normal apps that would be rare--you would use DI for IOptions and you would get the correct one based on the current tenant.

I could see that it would be useful to get options for a particular tenant other than the current one (similar to how if might be easier to clear them per your original post). I think I will add a way to do this.

**Comment by chernihiv** [comment]
Thanks you for full explanation, got it now, you are right.

I have multi tenant app, where each tenant have personal configuration, e.g OIDC. Therefore, I use extension method `WithPerTenantOptions<OpenIdConnectOptions>` to configure it per tenant (initialized first time and cached), however, configuration of OIDC per Tenant is hosted on separate server as microservices. 
Having updated this configuration, I ought to reset cache per tenant to be up-to-date. 
There are plenty workarounds, but it would be nice to have simple way to do it.
